name: "Winbox"
description: "Mikrotik router administration program"
version: "4.0beta3"
slug: "winbox"
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - "share"
options:
  user: "admin"
  address: ""
  password: ""
schema:
  user: "str"
  address: "str"
  password: "password"
image: "ghcr.io/soulripper13/{arch}-winbox"
webui: "http://[HOST]:[PORT:8099]"
ingress: true
ingress_port: 8099
panel_icon: "mdi:router-wireless"