name: "Winbox"
description: "MikroTik Winbox GUI via noVNC â€“ Manage your routers in a browser."
version: "1.0.0"
slug: winbox
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
init: false
ingress: true
ingress_port: 80
homeassistant_api: true
iot_class: localpoller
is_port_exclusive: false
host_network: false
audio: null
map:
  - media:rw
  - ssl:ro
  - addon_logs:ro
  - backup:ro
  - share:rw
ports:
  80/tcp: null  # noVNC web interface (HA ingress proxy)
schema:
  vnc_password: str?
  log_level: list(DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL)
